# Generated by Django 2.2.12 on 2020-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20200603_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalog_expiredate',
        ),
        migrations.AddField(
            model_name='catalog',
            name='expiredate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'Accepted'), (2, 'Rejected')], default=1, verbose_name='Статус'),
        ),
    ]
