# Generated by Django 2.2.12 on 2020-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20200608_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'Accepted'), (2, 'Rejected')], default=0, verbose_name='Статус'),
        ),
    ]
