# Generated by Django 2.2.12 on 2020-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20200608_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
